name: R-Stats-environment
channels:
 - conda-forge
 - bioconda
dependencies:
  - jupyter
  - jupyterlab
  - r-base=4.2
  # For data-cleanup and multivariate stats:
  - r-tidyverse
  - r-data.table
  - r-irkernel
  - r-vegan
  - r-IRdisplay
  - r-svglite
  - r-factoextra
  - r-ggrepel
  - r-KODAMA
  # For univariate stats:
  - r-ggsci
  - r-matrixStats
  - r-cowplot
  - r-FSA
  # For clustering & heatmaps
  - r-BiocManager
  - bioconductor-ComplexHeatmap
  - r-dendextend
  - r-NbClust

  # For supervised classification using xgboost
  - r-xgboost
  - r-caret
  - r-pROC
  - r-doParallel

